CREATE DATABASE `qqta` DEFAULT CHARACTER SET utf8mb4;

USE `qqta`;

DROP TABLE IF EXISTS `board`;

CREATE TABLE `board`(
  `seq` INT NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `reg_date` VARCHAR(100),
  `readCount` INT,
  PRIMARY KEY (`seq`));

INSERT INTO BOARD (SEQ, SUBJECT, CONTENT, NAME, READCOUNT) VALUES (1, 'TEST_SUBJECT1', 'TEST', 'k', 0);
INSERT INTO BOARD (SEQ, SUBJECT, CONTENT, NAME, READCOUNT) VALUES (2, 'TEST_SUBJECT2', 'TEST', 'k', 0);
INSERT INTO BOARD (SEQ, SUBJECT, CONTENT, NAME, READCOUNT) VALUES (3, 'TEST_SUBJECT3', 'TESt', 'k', 0);
INSERT INTO BOARD (SEQ, SUBJECT, CONTENT, NAME, READCOUNT) VALUES (4, 'TEST_SUBJECT4', 'Test', 'k', 0);
INSERT INTO BOARD (SEQ, SUBJECT, CONTENT, NAME, READCOUNT) VALUES (5, 'TEST_SUBJECT5', 'TESt', 'k', 0);